# Problem 1 

In [27]:
# 1 - numpy kütüphanesini import edin
import numpy as np
# 2 - 5 elemanlı bir numpy array oluşturun
array1 = np.array([2,5,8,923,45])
# 3 - Oluşturduğunuz arrayi küçükten büyüğe sıralayın.
array1.sort()
print(array1)


[  2   5   8  45 923]


# Problem 2

In [12]:
# 1- (10,15,30,45,60) değerlerine sahip numpy dizisi oluşturunuz.
import numpy as np
numpy_dizisi = np.array([10,15,30,45,60])
print(numpy_dizisi)

# 2- (5-15) arasındaki sayılarla numpy dizisi oluşturunuz. 

numpy_dizisi1 = np.arange(5,15,1)    #Belirli bir aralıkta sayı oluşturmak istiyorsam arrange fonksiyonunu kullanırım.
print(numpy_dizisi1)


# 3- (50-100) arasında 5'er 5'er artarak numpy dizisi oluşturunuz.

numpy_dizisi2 = np.arange(5,500,5)
print(numpy_dizisi2)


# 4- 10 elemanlı sıfırlardan oluşan bir dizi oluşturunuz.

zeros_numpy = np.zeros(10)
print(zeros_numpy)

# 5- 10 elemanlı birlerden oluşan bir dizi oluşturunuz.
ones_numpy = np.ones(10)
print(ones_numpy)
# 6- (0-100) arasında eşit aralıklı 5 sayı üretin.
linspace_numpy = np.linspace(0,100,5)
print(linspace_numpy)

# 7- (10-30) arasında rastgele 5 tane tamsayı üretin.
random = np.random.randint(10,30,5)
print(random)

# 8- [-1 ile 1] arasında 10 adet sayı üretin.
sayilar = np.random.uniform(-1, 1, 10)
print(sayilar)


# 9- (3x5) boyutlarında (10-50) arasında rastgele bir matris oluşturunuz.

matris = np.random.randint(10,50,(3,5))
print(matris)


# 10- Üretilen matrisin satır ve sütun sayıları toplamlarını hesaplayınız ?
satir_toplam = np.sum(matris, axis=1)
print(satir_toplam)
sutun_toplam = np.sum(matris, axis=0)
print(sutun_toplam)

# 11- Üretilen matrisin en büyük, en küçük ve ortalaması nedir ?
en_buyuk = np.max(matris)
print("Matrisin en büyük değeri=", en_buyuk)
en_kucuk = np.min(matris)
print("Matrisin en küçük değeri=", en_kucuk)
ortalama = np.mean(matris)
print("Matrisin ortalaması=", ortalama)

# 12- Üretilen matrisin en büyük değerinin indeksi kaçtır ?
index = np.argmax(matris)
print(index)

# 13- (10-20) arasındaki sayıları içeren dizinin ilk 3 elemanını seçiniz.
numbers = np.random.randint(10,20,size=8)
print(numbers[:3])

# 14- Üretilen dizinin elemanlarını tersten yazdırın.
print(numbers[::-1])

# 15- Üretilen matrisin ilk satırını seçiniz.
print(matris[0])

# 16- Üretilen matrisin 2.satır 3.sütundaki elemanı hangisidir ?
print(matris[1,2])

# 17- Üretilen matrisin tüm satırlardaki ilk elemanı seçiniz.
print(matris[:,0])

# 18- Üretilen matrisin her bir elemanının karesini alınız.
print(matris**2)

# 19- Üretilen matris elemanlarının hangisi pozitif çift sayıdır ? Aralığı (-50,+50) arasında yapınız.
matris1 = np.random.randint(-50,50, size=(3,5))
print(matris[(matris > 0) & (matris % 2 == 0)])

[10 15 30 45 60]
[ 5  6  7  8  9 10 11 12 13 14]
[  5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85  90
  95 100 105 110 115 120 125 130 135 140 145 150 155 160 165 170 175 180
 185 190 195 200 205 210 215 220 225 230 235 240 245 250 255 260 265 270
 275 280 285 290 295 300 305 310 315 320 325 330 335 340 345 350 355 360
 365 370 375 380 385 390 395 400 405 410 415 420 425 430 435 440 445 450
 455 460 465 470 475 480 485 490 495]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[  0.  25.  50.  75. 100.]
[18 25 18 12 17]
[-0.77395795  0.68401584 -0.83809093 -0.37695888 -0.03366913  0.57549803
  0.01371688  0.74023291  0.46984058 -0.98391205]
[[12 25 29 22 22]
 [12 43 12 47 24]
 [38 22 43 17 37]]
[110 138 157]
[62 90 84 86 83]
Matrisin en büyük değeri= 47
Matrisin en küçük değeri= 12
Matrisin ortalaması= 27.0
8
[12 15 16]
[13 19 11 19 11 16 15 12]
[12 25 29 22 22]
12
[12 12 38]
[[ 144  625  841  484  484]
 [ 144 1849  144 2209  576]
 [1444  484 1849  289