# Problem 1

In [5]:
pip install numpy


     -------------------------------------- 14.8/14.8 MB 215.5 kB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.3.1 -> 23.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [12]:
# 1 - numpy kütüphanesini import edin

import numpy as np

# 2 - 0 ile 10 arasında 5 sayıdan oluşan matris üretin
matris1 = np.random.randint(0,10,size=(5))
# 3 - matris'in boyutunu öğrenin
print(matris1.shape)
# 4 - matris'i yeniden boyutlandırın
matris1 = matris1.reshape(5,1)
# 5 - matris'in boyut sayısını öğrenin
print(matris1.ndim)

(5,)
2


# Problem 2

In [17]:
# 1 - 0 ile 10 arasında bulunan tek sayılardan oluşan matris üretin
matris2 = np.arange(1,10,2)
print(matris2) 
# 2 - Oluşturduğunuz matrisi parçalayın
x,y,z = np.split(matris2,[1,3])
print(x)
print(y)
print(z)
# 3 - Parçalanmış matrisleri birleştirin
print(np.concatenate([x,y,z]))


[1 3 5 7 9]
[1]
[3 5]
[7 9]
[1 3 5 7 9]


# Problem 3

In [22]:
# 1 - 5 ile 100 arasında ikişer ikişer atlayarak rastgele 10 sayıdan oluşan matris üretin
matris3 = np.random.choice(np.arange(5, 101, 2), size=(5, 2))
print(" matris:\n", matris3)
# 2 - matris'in özelliklerini inceleyiniz
print(matris3.ndim) 
print(matris3.shape)
print(matris3.size)
print(matris3.dtype)

 matris:
 [[39 91]
 [81 39]
 [77 57]
 [29 93]
 [15 63]]
2
(5, 2)
10
int32
